<?php
    $background_tiles = json_decode('
    {
        "0":
        {
            "name":"air",
            "texture":"air.png",
            "drops":[],
            "hardness":0,
            "mineable":"no",
            "tool":"none"
        },
        "1":
        {
            "name":"grass",
            "texture":"grass.png",
            "drops":[],
            "mineable":"no",
            "hardness":0,
            "tool":"none"
        },
        "2":
        {
            "name":"water",
            "texture":"water.png",
            "drops":[],
            "mineable":"no",
            "hardness":0,
            "tool":"none"
        },
        "3":
        {
            "name":"sand",
            "texture":"sand.png",
            "drops":[],
            "mineable":"no",
            "hardness":0,
            "tool":"none"
        },
        "4":
        {
            "name":"stone",
            "texture":"stone.png",
            "drops":[],
            "mineable":"no",
            "hardness":0,
            "tool":"none"
        }
    }
    ',true);
?>