<?php
    if(isset($_SESSION["num"])||$_SESSION["num"]="")
    {
        echo("aaa");
        $_SESSION["num"]=1;
    }
    if(isset($_SESSION["craftmode"])!=true)
    {
        $_SESSION["craftmode"]=null;
    }
    $_SESSION["background"];
?>